name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set SCRIPTS_DIR variable
        run: echo "SCRIPTS_DIR=/home/runner/work/DevOps/DevOps/scripts" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          chmod +x $SCRIPTS_DIR/configure-dependencies.sh
          $SCRIPTS_DIR/configure-dependencies.sh

      - name: Code formatting
        run: |
          chmod +x $SCRIPTS_DIR/format_code_black.sh
          $SCRIPTS_DIR/format_code_black.sh

      - name: Code quality check
        run: |
          chmod +x $SCRIPTS_DIR/check_quality_pylint.sh
          chmod +x $SCRIPTS_DIR/check_quality_flake8.sh
          chmod +x $SCRIPTS_DIR/check_quality_ruff.sh
          $SCRIPTS_DIR/check_quality_pylint.sh
          $SCRIPTS_DIR/check_quality_flake8.sh
          $SCRIPTS_DIR/check_quality_ruff.sh

      - name: Unit and functional testing
        run: |
          chmod +x $SCRIPTS_DIR/run_tests.sh
          $SCRIPTS_DIR/run_tests.sh

      - name: Tests coverage
        run: |
          chmod +x $SCRIPTS_DIR/run_tests.sh
          $SCRIPTS_DIR/run_tests.sh

      - name: Other tests
        run: |
          chmod +x $SCRIPTS_DIR/check_quality_radon.sh
          chmod +x $SCRIPTS_DIR/check_quality_bandit.sh
          $SCRIPTS_DIR/check_quality_radon.sh
          $SCRIPTS_DIR/check_quality_bandit.sh

      - name: Deploy to Heroku
        run: echo "Deploying to Heroku"
